### ISSUE TITLE
Some websites never trigger load event

### ISSUE THREAD

**Issue by rkoblev** [zfcsoftware/puppeteer-real-browser#60] opened 2024-06-05 12:33 UTC
It looks like the bug from "Timeout error when waiting for browser response #7" didn't fixed.
I'm getting navigation timeout even if page is completely loaded, and if I remove targetFilter then it works for this page (but doesn't work for CF pages). Example website [steensmalawn](https://www.steensmalawn.com)

**Comment by TheRealStingo** [comment] 2024-06-07 13:43
Same issues with some websites too

**Comment by zfcsoftware** [comment] 2024-06-07 15:53
> It looks like the bug from "Timeout error when waiting for browser response #7" didn't fixed. I'm getting navigation timeout even if page is completely loaded, and if I remove targetFilter then it works for this page (but doesn't work for CF pages). Example website [steensmalawn](https://www.steensmalawn.com)



> Same issues with some websites too


Hello, this problem is caused by targetFilter. targetFilter disables Puppeteer on the targets you specify. For this reason, sometimes timeOut problems can occur. This is a subject I have researched. 

https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/module/browser.js

You can use the browser here. Soon puppeteer-real-browser will launch the browser in this way. There will be an update that will solve most problems. I will update when I have time.

**Comment by benhab-i** [comment] 2024-06-08 12:29
> https://github.com/zfcsoftware/cf-clearance-scraper/blob/main/module/browser.js

You can use the browser here. Soon puppeteer-real-browser will launch the browser in this way. There will be an update that will solve most problems. I will update when I have time.

Hi, sorry but can you explain I don't understand how to fix that.

Running on windows, no problem at all 
`setTarget({ status: false });
            const spPage = await browser.newPage();
            await page.close();
            setTarget({ status: true });
            blocker.enableBlockingInPage(spPage);`
But on Linux, I have a timeout, and I can "fix the timeout" by removing this ` setTarget({ status: true });` but then turnstile is on error.

Thanks.

**Comment by zfcsoftware** [comment] 2024-07-26 18:12
https://github.com/zfcsoftware/cf-clearance-scraper/blob/22f3576bf0c7c23bf23425bdc0113b58e571f5d8/module/scrape.js#L99
Yes, this is an annoying bug. You can use page.goto like this for now. I am investigating this problem.

**Comment by zfcsoftware** [comment] 2024-08-23 03:26
The library has been updated. This issue should be resolved. Please test with the latest version 1.3.0. I'm closing this issue for now. If the problem persists, please send me a message through this issue and I'll reactivate it.

**Closed by zfcsoftware** 2024-08-23 03:26 UTC
Labels: bug
