### ISSUE TITLE
Cloudflare has caught up with PRB again

### ISSUE THREAD

**Issue by chooyanglee** [zfcsoftware/puppeteer-real-browser#116] opened 2024-08-07 21:53 UTC
Since today cloudflare no longer presents a challenge page when they detect puppeteer real browser, it seems we are missing something and they now don't bother with the challenge since we can solve it. Basically the it all stalls with a blank page (the one with the "__cf_chl_rt_tk" querystring). Does anyone also have this same issue?

**Comment by zfcsoftware** [comment] 2024-08-08 11:14
There is no known problem at the moment. I have encountered the error you mentioned in a few places like chatgpt. It should fix when you refresh the page. you can try page.reload.

**Comment by chooyanglee** [comment] 2024-08-09 11:39
No joy, can you try this url: https://clubtek.pt/som-imagem/som-portatil-530/colunas-portateis-531?product_id=161504

It just seats there with a "Just a moment..." blank page, and this url used to work on Tuesday.

**Comment by zfcsoftware** [comment] 2024-08-13 14:51
I don't encounter a WAF on the site you provided. I can't reproduce the problem so I close this one. I've had this problem a few times but it doesn't happen all the time.

**Closed by zfcsoftware** 2024-08-13 14:51 UTC
