### ISSUE TITLE
Property 'executionContextId' of 'undefined'

### ISSUE THREAD

**Issue by Zvih** [zfcsoftware/puppeteer-real-browser#133] opened 2024-08-23 09:13 UTC
it seems, An error is triggered when the Cloudflare checkbox tries to be checked automatically for the second time
<img width="448" alt="image" src="https://github.com/user-attachments/assets/741140af-fe27-4220-91ef-cc5c6176a476">

**Comment by zfcsoftware** [comment] 2024-08-23 09:59
Can you add rebuild steps to the problem?

**Comment by Zvih** [comment] 2024-08-23 10:06
@zfcsoftware Setup as I provied here https://github.com/zfcsoftware/puppeteer-real-browser/issues/132 

Run browser, go to page.

Actually, nothing special, just open page with cloudflare checkbox and got error. But checkbox is checked so error does not interfere the lib

**Comment by bookedkeeper** [comment] 2024-08-24 02:11
Got the same error. It wasn't caught by a try/catch and crashed the script. Here's a trace:
```
TypeError: Cannot destructure property 'executionContextId' of 'undefined' as it is undefined.
    at <anonymous> ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:544:9)
    at async Promise.all (index 0)
    at FrameManager.#createIsolatedWorld ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:531:5)
    at async Promise.all (index 4)
    at FrameManager.initialize ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:210:63)
Node.js v20.16.0
```

Thanks for looking into this

**Comment by zfcsoftware** [comment] 2024-08-24 10:54
> @zfcsoftware Setup as I provied here #132
> 
> Run browser, go to page.
> 
> Actually, nothing special, just open page with cloudflare checkbox and got error. But checkbox is checked so error does not interfere the lib



> Got the same error. It wasn't caught by a try/catch and crashed the script. Here's a trace:
> 
> ```
> TypeError: Cannot destructure property 'executionContextId' of 'undefined' as it is undefined.
>     at <anonymous> ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:544:9)
>     at async Promise.all (index 0)
>     at FrameManager.#createIsolatedWorld ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:531:5)
>     at async Promise.all (index 4)
>     at FrameManager.initialize ([...]/node_modules/puppeteer-real-browser/lib/data/puppeteer-core/src/cdp/FrameManager.ts:210:63)
> Node.js v20.16.0
> ```
> 
> Thanks for looking into this

Can you give me a working code that I can test? The problem you posted has already been solved. The code there does not work because it is part of somewhere. I need a code that works and gives this error.

**Comment by Zvih** [comment] 2024-08-25 10:42
@zfcsoftware  Hardly possible to trace. It usually appears after logging in to the website with a Cloudflare checkbox and after navigating to several pages. Maybe other guy can provide more info

**Comment by zfcsoftware** [comment] 2024-08-27 20:54
I am closing the issue as it cannot be reproduced. If you find a way to reproduce it, please let me know here. Thank you.

**Comment by Zvih** [comment] 2024-08-28 11:24
@zfcsoftware

**Comment by zfcsoftware** [comment] 2024-08-28 21:38
> I have the same issue. Try this code:
> 
> ```
> const {browser, page} = await connect({
>         headless: "new",
>         turnstile: true,
>         disableXvfb: true, 
> });
> await page.setRequestInterception(true);
> page.on('request', request => {
>       if(request.isInterceptResolutionHandled()) return;
>       request.continue();
> });
> page.on("framenavigated", async (frame) => {
>       if(frame.url().includes("cloudflare")){
>           await client.send("Target.detachFromTarget", {
>               targetId: frame._id,
>           });
>       }
> });  
> await page.goto("https://keepa.com/#!product/1-B0C4VQXSMT");
> ```
> 
> If i don't use setRequestInterception, the error appears after quite a few iterations. This is the only way I've found to simulate the error quickly. I use Chrome/128.0.6613.85 and Node 18.15.0.



> @zfcsoftware


The library guarantees stable operation only when used with headless false. When using 'new' it can be detected and errors can occur. When I used false, I did not encounter an error in the code.

**Comment by Zvih** [comment] 2024-08-29 03:48
I use headless true/false and got this error sometimes

**Comment by Zvih** [comment] 2024-08-31 07:05
@zfcsoftware  Hi there,
Does lib started supporting both  true/false value for "headless" param ?

**Comment by zfcsoftware** [comment] 2024-08-31 12:38
The library is not guaranteed to work except false but it does support it.

**Comment by Zvih** [comment] 2024-09-01 17:05
@zfcsoftware Should I start a new topic about support for headless: true, or are there no plans to fix that issue?

**Comment by CarbonPool** [comment] 2024-09-07 02:19
Re-updating the pptr patch solved my problem

**Comment by zfcsoftware** [comment] 2024-09-07 02:43
Can you try again with the latest version?

**Comment by zfcsoftware** [comment] 2024-09-07 11:32
https://github.com/zfcsoftware/puppeteer-real-browser/issues/162#issuecomment-2335126867

**Closed by zfcsoftware** 2024-09-07 11:32 UTC
