### ISSUE TITLE
Turnstile not working anymore

### ISSUE THREAD

**Issue by ledean** [zfcsoftware/puppeteer-real-browser#84] opened 2024-07-08 18:49 UTC
Doesnt matter with/without proxy, its not clicking the box anymore

**Comment by zfcsoftware** [comment] 2024-07-08 18:52
Which site? Which operating system?

**Comment by EgglezosK** [comment] 2024-07-08 18:58
@zfcsoftware From today the iframe for some reason will be not detected on the code thats the problem, i investigate it also.

**Comment by 0-don** [comment] 2024-07-08 19:04
yes having same issue currently

**Comment by zfcsoftware** [comment] 2024-07-08 19:21
It should be fixed. Please check with the latest version.

**Comment by EgglezosK** [comment] 2024-07-08 19:45
> It should be fixed. Please check with the latest version.

Its working now! ( I still have the same issue while using proxies thought )

**Comment by 0-don** [comment] 2024-07-08 19:46
> > It should be fixed. Please check with the latest version.
> 
> Its working now! ( I still have the same issue while using proxies thought )

you need to rotate more it still works just takes time

**Comment by zfcsoftware** [comment] 2024-07-08 19:49
> > It should be fixed. Please check with the latest version.
> 
> Its working now! ( I still have the same issue while using proxies thought )



> > > It should be fixed. Please check with the latest version.
> > 
> > 
> > Its working now! ( I still have the same issue while using proxies thought )
> 
> you need to rotate more it still works just takes time

I started to have problems with spinning more and consuming a lot of cpu. I'm looking for a solution, it's an open source library so I don't have much time, but I'll make some nice updates when I have time.

It works even with a proxy. I have tested this many times but I have not encountered an error. If you can send me a code and a vps provider that can reproduce the problem, I can do the tests. However, I did not see a problem in my tests.

**Comment by EgglezosK** [comment] 2024-07-08 19:56
> > > It should be fixed. Please check with the latest version.
> > 
> > 
> > Its working now! ( I still have the same issue while using proxies thought )
> 
> > > > It should be fixed. Please check with the latest version.
> > > 
> > > 
> > > Its working now! ( I still have the same issue while using proxies thought )
> > 
> > 
> > you need to rotate more it still works just takes time
> 
> I started to have problems with spinning more and consuming a lot of cpu. This and other cf migration methods can do this occasionally. I'm looking for a solution, it's an open source library so I don't have much time, but I'll make some nice updates when I have time.
> 
> It works even with a proxy. I have tested this many times but I have not encountered an error. If you can send me a code and a vps provider that can reproduce the problem, I can do the tests. However, I did not see a problem in my tests.

I am going to send you on private email right now. In the Email you will find also an openvpn file that you can use and run your library without proxies, and you will be noticed that the same problem will appear, spinning and reload again and again until timeout.

**Comment by cod888** [comment] 2024-07-08 20:22
Confirm the above comment. The last solution fixed the clicking issue, but spinning is still there for some (marked as suspicions) proxies. it worked before the CF made the latest updates.

**Comment by zfcsoftware** [comment] 2024-07-08 20:25
> Confirm the above comment. The last solution fixed the clicking issue, but spinning is still there for some (marked as suspicions) proxies. it worked before the CF made the latest updates.

https://blog.cloudflare.com/residential-proxy-bot-detection-using-machine-learning/
I think that's it. The problem seems to be the proxy, not the library.

**Comment by cod888** [comment] 2024-07-08 20:26
I used ISP proxies but maybe they don't care about it :)

**Comment by zfcsoftware** [comment] 2024-07-08 20:29
> I used ISP proxies but maybe they don't care about it :) anyway .. with manual clicking it still working with these proxies btw

Then the problem may be targetFilter or xvfb. 
https://www.npmjs.com/package/ghost-cursor
Have you tried with this library? In the last update the library clicks with the mouse.

**Comment by zfcsoftware** [comment] 2024-07-08 20:49
> I used ISP proxies but maybe they don't care about it :) anyway .. with manual clicking it still working with these proxies btw



> > > > It should be fixed. Please check with the latest version.
> > > 
> > > 
> > > Its working now! ( I still have the same issue while using proxies thought )
> > 
> > 
> > > > > It should be fixed. Please check with the latest version.
> > > > 
> > > > 
> > > > Its working now! ( I still have the same issue while using proxies thought )
> > > 
> > > 
> > > you need to rotate more it still works just takes time
> > 
> > 
> > I started to have problems with spinning more and consuming a lot of cpu. This and other cf migration methods can do this occasionally. I'm looking for a solution, it's an open source library so I don't have much time, but I'll make some nice updates when I have time.
> > It works even with a proxy. I have tested this many times but I have not encountered an error. If you can send me a code and a vps provider that can reproduce the problem, I can do the tests. However, I did not see a problem in my tests.
> 
> I am going to send you on private email right now. In the Email you will find also an openvpn file that you can use and run your library without proxies, and you will be noticed that the same problem will appear, spinning and reload again and again until timeout.



> I used ISP proxies but maybe they don't care about it :) anyway .. with manual clicking it still working with these proxies btw

Could it be that it checks the browser more thoroughly for suspicious ip addresses? 
https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/159.146.35.11
The problem does not recur on my computer, but could you please test with a proxy that has a very low spam score on this site?

**Comment by cod888** [comment] 2024-07-08 20:57
I can confirm that with not so suspicious proxies the lib is working.

**Comment by zfcsoftware** [comment] 2024-07-08 21:00
> I can confirm that with not so suspicious proxies the lib is working.

Then the problem seems to be caused by Cloudflare's proxy update.
@EgglezosK Do you have the same situation? Probably when you tested without using a proxy, your home ip address was clean so it allowed the transition. Can you test with a clean ip address? A lot of cpu consumption, long hold time and constant page refresh may be a proxy score issue.

**Comment by EgglezosK** [comment] 2024-07-08 21:25
> > I can confirm that with not so suspicious proxies the lib is working.
> 
> Then the problem seems to be caused by Cloudflare's proxy update. @EgglezosK Do you have the same situation? Probably when you tested without using a proxy, your home ip address was clean so it allowed the transition. Can you test with a clean ip address? A lot of cpu consumption, long hold time and constant page refresh may be a proxy score issue.

i just check all my proxies and all are 99 - High Risk from webshare. with my local ip and https://nopecha.com/captcha/cloudflare it seems to works as i told before. The weird part of the story is that when you set turnstile:false and you use a Hight Risk Proxy it by pass it

**Comment by zfcsoftware** [comment] 2024-07-08 21:27
> > > I can confirm that with not so suspicious proxies the lib is working.
> > 
> > 
> > Then the problem seems to be caused by Cloudflare's proxy update. @EgglezosK Do you have the same situation? Probably when you tested without using a proxy, your home ip address was clean so it allowed the transition. Can you test with a clean ip address? A lot of cpu consumption, long hold time and constant page refresh may be a proxy score issue.
> 
> i just check all my proxies and all are 99 - High Risk from webshare. with my local ip and https://nopecha.com/captcha/cloudflare it seems to works as i told before. The weird part of the story is that when you set turnstile:false and you use a Hight Risk Proxy it by pass it

Maybe they are tracking the mouse on risky ip addresses. Obviously they update very often and monitor all libraries. Right now this library has a CDP detection problem. I will fix that soon. In the meantime, I have 100% spam scoring proxies on webshare that allow me to pass through. It's a strange situation.

**Comment by cod888** [comment] 2024-07-08 21:30
> > > > I can confirm that with not so suspicious proxies the lib is working.
> > > 
> > > 
> > > Then the problem seems to be caused by Cloudflare's proxy update. @EgglezosK Do you have the same situation? Probably when you tested without using a proxy, your home ip address was clean so it allowed the transition. Can you test with a clean ip address? A lot of cpu consumption, long hold time and constant page refresh may be a proxy score issue.
> > 
> > 
> > i just check all my proxies and all are 99 - High Risk from webshare. with my local ip and https://nopecha.com/captcha/cloudflare it seems to works as i told before. The weird part of the story is that when you set turnstile:false and you use a Hight Risk Proxy it by pass it
> 
> Maybe they are tracking the mouse on risky ip addresses. Obviously they update very often and monitor all libraries. Right now this library has a CDP detection problem. I will fix that soon. In the meantime, I have 100% spam scoring proxies on webshare that allow me to pass through. It's a strange situation.

it works with 100% spammy proxies because you have that fix for cdp. we can check it when you push it :-)

**Comment by EgglezosK** [comment] 2024-07-08 21:32
> > > > I can confirm that with not so suspicious proxies the lib is working.
> > > 
> > > 
> > > Then the problem seems to be caused by Cloudflare's proxy update. @EgglezosK Do you have the same situation? Probably when you tested without using a proxy, your home ip address was clean so it allowed the transition. Can you test with a clean ip address? A lot of cpu consumption, long hold time and constant page refresh may be a proxy score issue.
> > 
> > 
> > i just check all my proxies and all are 99 - High Risk from webshare. with my local ip and https://nopecha.com/captcha/cloudflare it seems to works as i told before. The weird part of the story is that when you set turnstile:false and you use a Hight Risk Proxy it by pass it
> 
> Maybe they are tracking the mouse on risky ip addresses. Obviously they update very often and monitor all libraries. Right now this library has a CDP detection problem. I will fix that soon. In the meantime, I have 100% spam scoring proxies on webshare that allow me to pass through. It's a strange situation.

if you want share one of these with me via mail to check the results of it.

**Comment by CValeron** [comment] 2024-07-09 07:51
> It should be fixed. Please check with the latest version.

I have updated and working now with proxy. Thank you very much

**Comment by EgglezosK** [comment] 2024-07-09 07:52
> > It should be fixed. Please check with the latest version.
> 
> I have updated and working now with proxy. Thank you very much

what kind of proxy?

**Comment by CValeron** [comment] 2024-07-09 07:55
webshare free version

**Comment by mrcas** [comment] 2024-07-09 18:38
Cannot pass https://chatgpt.com

**Closed** 2024-07-09 20:12 UTC
