### ISSUE TITLE
Multiple Browser issue

### ISSUE THREAD

**Issue by sharpanimes** [zfcsoftware/puppeteer-real-browser#33] opened 2024-04-08 03:08 UTC
when i am running the script twice at same time from different terminals using different userDatadir, it is getting linked to the same chrome...
How to open two different browsers?

**Comment by zfcsoftware** [comment] 2024-04-16 16:06
Hello, if you import the library with await import every time you start a project, it will not be related to each other. Soon the project will be transferred to the class structure, this problem will not be left, but until then you can try importing every time you will use it. I can support you if you can add your code. No one has reported having this kind of problem before.

**Comment by sharpanimes** [comment] 2024-04-19 11:53
sorry for my confusion i was incorrectly stating the data directory.
```
 const response = await connect({
        headless: 'auto',
        args: [
            `--proxy-server=${proxyURL}`,
        ],
        customConfig: {
            userDataDir: 'myUserDataDir',
        },
        skipTarget: [],
        fingerprint: true,
        turnstile: true,
        connectOption: {
            userDataDir: 'myUserDataDir',
        },
        tf: false
    });
```
i was sending the userData dir in the connect option which i figured out didnt actually do anything, the correct way was to define it in the customConfig option.

One more issue which i noticed is if i define a new userDataDirectory which doesnt exist, the puppeter real throws a error 
`
Error: ENOENT: no such file or directory, open 'myUserDataDir2/chrome-out.log'`
I fixed it by manually creating a directory by using the original puppeter and let it run once.
Then revert back to puppeter-real browser and use it

**Closed** 2024-05-05 07:06 UTC

**Comment by zfcsoftware** [comment] 2024-05-05 08:03
> sorry for my confusion i was incorrectly stating the data directory.
> 
> ```
>  const response = await connect({
>         headless: 'auto',
>         args: [
>             `--proxy-server=${proxyURL}`,
>         ],
>         customConfig: {
>             userDataDir: 'myUserDataDir',
>         },
>         skipTarget: [],
>         fingerprint: true,
>         turnstile: true,
>         connectOption: {
>             userDataDir: 'myUserDataDir',
>         },
>         tf: false
>     });
> ```
> 
> i was sending the userData dir in the connect option which i figured out didnt actually do anything, the correct way was to define it in the customConfig option.
> 
> One more issue which i noticed is if i define a new userDataDirectory which doesnt exist, the puppeter real throws a error ` Error: ENOENT: no such file or directory, open 'myUserDataDir2/chrome-out.log'` I fixed it by manually creating a directory by using the original puppeter and let it run once. Then revert back to puppeter-real browser and use it


I am glad that the problem is solved. Since puppeteer is run with .connect, some of its properties may be incorrect.  I am working on many bugs, I will try to fix them, thanks for your contribution.
